---
- name: ensure file_sd on prometheus host
  file:
    path: "/etc/prometheus/file_sd/node-exporter"
    state: directory
  loop: "{{ node_exporter_prometheus_hosts }}"
  delegate_to: "{{ item }}"
  become: true

- name: ensure sd yml o prometheus host
  template:
    src: "file_sd.yml.j2"
    dest: "/etc/prometheus/file_sd/node-exporter/{{ inventory_hostname }}.yml"
  loop: "{{ node_exporter_prometheus_hosts }}"
  delegate_to: "{{ item }}"
  become: true
