---
- name: ensure node-exporter package
  include_role:
    name: "damex.package"
  vars:
    package_packages:
      - name: "{{ node_exporter_package_name }}"
        version: "{{ node_exporter_package_version }}"
        state: "{{ node_exporter_package_state }}"
